sudo: true
language: php
php:
  - 7.2
  - 7.3

env:
  - TESTSUITE=kernel
  - TESTSUITE=functional
  - TESTSUITE=functional-javascript

matrix:
    fast_finish: true
    allow_failures:
      - php: 7.3

services:
  - mysql

branches:
  only:
    - /^8.x/
    - /master/

before_install:
  - export SCRIPT_DIR=$HOME/islandora_ci
  - export DRUPAL_DIR=/opt/drupal
  - export PHPUNIT_FILE=$TRAVIS_BUILD_DIR/phpunit.xml
  - export COMPOSER_PATH="/home/travis/.phpenv/versions/$TRAVIS_PHP_VERSION/bin/composer"
  - phpenv config-rm xdebug.ini

install:
  - git clone https://github.com/Islandora/islandora_ci.git $HOME/islandora_ci
  - $SCRIPT_DIR/travis_setup_drupal.sh
  - git -C "$TRAVIS_BUILD_DIR" checkout -b travis-testing
  - cd $DRUPAL_DIR;
  - chmod -R u+w web/sites/default
  - COMPOSER_MEMORY_LIMIT=-1 php -d memory_limit=-1 $COMPOSER_PATH config repositories.local path "$TRAVIS_BUILD_DIR"
  - COMPOSER_MEMORY_LIMIT=-1 php -d memory_limit=-1 $COMPOSER_PATH require "islandora/islandora:dev-travis-testing as dev-8.x-1.x" --prefer-source --update-with-all-dependencies
  - cd web
  - drush --uri=127.0.0.1:8282 en -y islandora_audio islandora_breadcrumbs islandora_iiif islandora_image islandora_video islandora_text_extraction_defaults
  - drush --uri=127.0.0.1:8282 fim -y islandora_core_feature,islandora_text_extraction_defaults
  - mkdir -p $DRUPAL_DIR/web/sites/simpletest/browser_output
  - cp $PHPUNIT_FILE $DRUPAL_DIR/web/core/phpunit.xml

script:
  - $SCRIPT_DIR/travis_scripts.sh
  - cd $DRUPAL_DIR/web/core
  - $DRUPAL_DIR/vendor/bin/phpunit --verbose --testsuite "$TESTSUITE"

notifications:
  slack:
    on_success: change
    on_failure: always
    secure: $SLACK_NOTIFICATION_KEY
