sudo: true
language: php
php:
  - 7.2
  - 7.3

matrix:
    fast_finish: true
    allow_failures:
      - php: 7.3
      
services:
  - mysql

branches:
  only:
    - /^8.x/
    - /master/

before_install:
  - export SCRIPT_DIR=$HOME/CLAW/.scripts
  - export DRUPAL_DIR=/opt/drupal
  - export COMPOSER_PATH="/home/travis/.phpenv/versions/$TRAVIS_PHP_VERSION/bin/composer"

install:
  - git clone https://github.com/Islandora-CLAW/CLAW.git $HOME/CLAW
  - $SCRIPT_DIR/travis_setup_drupal.sh
  - git -C "$TRAVIS_BUILD_DIR" checkout -b travis-testing
  - cd $DRUPAL_DIR;
  - COMPOSER_MEMORY_LIMIT=-1 php -d memory_limit=-1 $COMPOSER_PATH config repositories.local path "$TRAVIS_BUILD_DIR"
  - COMPOSER_MEMORY_LIMIT=-1 php -d memory_limit=-1 $COMPOSER_PATH require "islandora/islandora:dev-travis-testing as dev-8.x-1.x" --prefer-source --update-with-dependencies
  - cd web; drush --uri=127.0.0.1:8282 en -y islandora
  - (drush -y --uri=127.0.0.1:8282 en islandora_core_feature; drush -y --uri=127.0.0.1:8282 fim islandora_core_feature)
  - drush -y --uri=127.0.0.1:8282 en islandora_audio islandora_breadcrumbs islandora_iiif islandora_image islandora_video
  - (drush -y --uri=127.0.0.1:8282 en islandora_text_extraction_defaults; drush -y --uri=127.0.0.1:8282 fim islandora_text_extraction_defaults)

script:
  - $SCRIPT_DIR/travis_scripts.sh
  - $SCRIPT_DIR/run-tests.sh "islandora"
  - $SCRIPT_DIR/run-tests.sh "islandora_breadcrumbs"

notifications:
  irc:
    channels:
      - "irc.freenode.org#islandora"
    on_success: change
    on_failure: always
    skip_join: true
